Subscribe
R3enox/Simply-Chocolate pull request #2
Opened 2023-06-16 05:18 UTC by YuliiaPro

Add subscribe section

2023-06-16 15:36 UTC, R3enox requested changes
https://www.loom.com/share/219036b57eef47bc9cb41b4ac4e6c7d5?sid=da083802-9d78-4144-9cd6-69923629cb57

2023-06-16 18:24 UTC, YuliiaPro commented
Зауваження по секції Subscribe виправила

2023-06-17 04:52 UTC, R3enox approved these changes
good job :)

2023-06-17 04:53 UTC, R3enox commented
Нужно исправить незначительные ошибки
https://www.loom.com/share/9b4f0ee0432740cbb34e2c2e72f17c7f?sid=3a0ee0ab-8e69-4955-8afd-2c755b4fac41

2023-06-17 04:53 UTC, merged